# Generated by Django 3.0.4 on 2020-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bollywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('screenshot1', models.ImageField(upload_to='')),
                ('screenshot2', models.ImageField(upload_to='')),
                ('screenshot3', models.ImageField(upload_to='')),
                ('torrent', models.TextField()),
                ('magnet', models.TextField()),
                ('direct', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hollywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('torrent', models.TextField()),
                ('magnet', models.TextField()),
                ('direct', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('direct', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pcgames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('torrent', models.TextField()),
                ('direct', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='supersearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('screenshot1', models.ImageField(upload_to='')),
                ('screenshot2', models.ImageField(upload_to='')),
                ('screenshot3', models.ImageField(upload_to='')),
                ('torrent', models.TextField()),
                ('magnet', models.TextField()),
                ('direct', models.TextField()),
            ],
        ),
    ]
